name: JS Lint

on:
  push:
    branches:
      - master
      - lint-test
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@1.0.2
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
